homework
babenko-alex-pdffiller/gocourse03 pull request #2
Opened 2024-08-16 12:59 UTC by babenko-alex-pdffiller

2024-08-16 13:55 UTC, alexandear requested changes
Завдання домашки містить текст: "Виконати операції видалення, пошуку і додавання в слайс"

Чи не міг би додати операції видалення і пошуку зі слайсу? Додавання знайшов.

Приклади різних операцій зі слайсами є тут https://go.dev/wiki/SliceTricks

2024-08-23 15:24 UTC, alexandear requested changes

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +		{SectorID: TopLeft, HasSensor: false, Morning: SectorState{Times: Morning}, Afternoon: SectorState{Times: Afternoon}, Evening: SectorState{Times: Evening}},
Важкувато читати та модифікувати. Пропоную ось так:
```suggestion
		{
			SectorID:  TopLeft,
			HasSensor: false,
			Morning:   SectorState{Times: Morning},
			Afternoon: SectorState{Times: Afternoon},
			Evening:   SectorState{Times: Evening},
		},
```

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +	rodentId := rand.IntN(len(rodents)) + 1
```suggestion
	rodentID := rand.IntN(len(rodents)) + 1
```

Ось тут https://go.dev/wiki/CodeReviewComments#initialisms написано, чому так:
> Words in names that are initialisms or acronyms (e.g. “URL” or “NATO”) have a consistent case. For example, “URL” should appear as “URL” or “url” (as in “urlPony”, or “URLPony”), never as “Url”. As an example: ServeHTTP not ServeHttp. For identifiers with multiple initialized “words”, use for example “xmlHTTPRequest” or “XMLHTTPRequest”.

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +		for is, _ := range sectors {
можна простіше:
```suggestion
		for is := range sectors {
```

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +func printRodentLocation(rodent Rodent) {
Треба розділяти функції пустими рядками, щоб краще читалось.

```suggestion
}

func printRodentLocation(rodent Rodent) {
```

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +func printRodentLocation(rodent Rodent) {
Можна поставити собі gofumpt, який автоматично це робитиме.

В Slack писав:
https://golang-beginning-6.slack.com/archives/C07EVP8S4FK/p1724071944955179

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +func getSectorID(location *Location) SectorID {
Чи можемо ми зробити цю функцію методом структури `Location`?

Типу:

```go
type Location struct {
	// ...
}

func (l *Location) getSectorID() SectorID {
	// ...
}

2024-08-23 15:24 UTC, alexandear commented on tasks/homework.go
> +			printRodentLocation(rodent)
Чи можемо трішки переробити код, щоб працювало наступне?
```suggestion
			rodent.printLocation()
```

2024-08-26 10:27 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +		for is, _ := range sectors {
так, дісно, видалив зайве

2024-08-26 10:27 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +func printRodentLocation(rodent Rodent) {
додав

2024-08-26 10:31 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +func getSectorID(location *Location) SectorID {
так, змінив

2024-08-26 20:11 UTC, alexandear approved these changes
LGTM

Можна мерджити, тільки виправ одну помилку.

2024-08-26 20:11 UTC, alexandear commented on tasks/homework.go
> +func buildSercors() []Sector {
Помилочка:
```suggestion
func buildSectors() []Sector {
```

2024-08-31 12:06 UTC, merged